### ISSUE TITLE
Logo Sizing

### ISSUE THREAD

**Issue by generallynonsensical** [howbea/logo-widget#1]
Logo size maxed out in settings is still quite small, regardless of input file size. Perhaps allow files to be scaled a substantial amount higher res? I've tried a png and a svg and can't get it to scale up to a size I would like.

Sys Info:

Debian 12: Bookworm
Kernel: 6.1.0-12
Desktop: Gnome 43.9
Display: x11
2560X1440
RTX 2060

**Comment by howbea** [comment]
Hi.
Thank you for request.
It was updated for sizing and positioning.
I hope you enjoy.

**Comment by generallynonsensical** [comment]
Brilliant. Thank you. 😊
